#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from Yacc.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "Yacc.y"

#include <stdio.h>
#include <stdlib.h>

extern FILE* yyin; // Declare an external file pointer for input

FILE* fsread; // Declare file pointers for reading and writing
FILE* fswrite;

int yylex(void); // Declare the lexer function
int yyerror(); // Declare the error handling function

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ID	258
#define	LPAR	259
#define	RPAR	260
#define	LT	261
#define	GT	262
#define	INT	263
#define	FLOAT	264
#define	CHAR	265
#define	STRING	266
#define	BOOL	267
#define	DOUBLE	268
#define	LONG	269
#define	VOID	270
#define	NODE	271
#define	BTREE	272
#define	BSTREE	273
#define	COMMA	274
#define	LFB	275
#define	RFB	276
#define	SEMICOLON	277
#define	LSB	278
#define	RSB	279
#define	NUMBER	280
#define	EQUAL	281
#define	AND	282
#define	OR	283
#define	LOR	284
#define	LAND	285
#define	LXOR	286
#define	GEQ	287
#define	LEQ	288
#define	NE	289
#define	EQ	290
#define	STRINGC	291
#define	CHARC	292
#define	ADD	293
#define	SUB	294
#define	MUL	295
#define	DIV	296
#define	MOD	297
#define	DECIMAL	298
#define	FLOATING	299
#define	DOT	300
#define	BREAK	301
#define	CONTINUE	302
#define	RETURN	303
#define	INCR	304
#define	DECR	305
#define	IF	306
#define	ELSE	307
#define	WHILE	308
#define	FOR	309
#define	LNULL	310
#define	NEG	311
#define	LTRUE	312
#define	LFALSE	313


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ID;
static const int LPAR;
static const int RPAR;
static const int LT;
static const int GT;
static const int INT;
static const int FLOAT;
static const int CHAR;
static const int STRING;
static const int BOOL;
static const int DOUBLE;
static const int LONG;
static const int VOID;
static const int NODE;
static const int BTREE;
static const int BSTREE;
static const int COMMA;
static const int LFB;
static const int RFB;
static const int SEMICOLON;
static const int LSB;
static const int RSB;
static const int NUMBER;
static const int EQUAL;
static const int AND;
static const int OR;
static const int LOR;
static const int LAND;
static const int LXOR;
static const int GEQ;
static const int LEQ;
static const int NE;
static const int EQ;
static const int STRINGC;
static const int CHARC;
static const int ADD;
static const int SUB;
static const int MUL;
static const int DIV;
static const int MOD;
static const int DECIMAL;
static const int FLOATING;
static const int DOT;
static const int BREAK;
static const int CONTINUE;
static const int RETURN;
static const int INCR;
static const int DECR;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int LNULL;
static const int NEG;
static const int LTRUE;
static const int LFALSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ID=258
	,LPAR=259
	,RPAR=260
	,LT=261
	,GT=262
	,INT=263
	,FLOAT=264
	,CHAR=265
	,STRING=266
	,BOOL=267
	,DOUBLE=268
	,LONG=269
	,VOID=270
	,NODE=271
	,BTREE=272
	,BSTREE=273
	,COMMA=274
	,LFB=275
	,RFB=276
	,SEMICOLON=277
	,LSB=278
	,RSB=279
	,NUMBER=280
	,EQUAL=281
	,AND=282
	,OR=283
	,LOR=284
	,LAND=285
	,LXOR=286
	,GEQ=287
	,LEQ=288
	,NE=289
	,EQ=290
	,STRINGC=291
	,CHARC=292
	,ADD=293
	,SUB=294
	,MUL=295
	,DIV=296
	,MOD=297
	,DECIMAL=298
	,FLOATING=299
	,DOT=300
	,BREAK=301
	,CONTINUE=302
	,RETURN=303
	,INCR=304
	,DECR=305
	,IF=306
	,ELSE=307
	,WHILE=308
	,FOR=309
	,LNULL=310
	,NEG=311
	,LTRUE=312
	,LFALSE=313


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::ID=258;
const int YY_parse_CLASS::LPAR=259;
const int YY_parse_CLASS::RPAR=260;
const int YY_parse_CLASS::LT=261;
const int YY_parse_CLASS::GT=262;
const int YY_parse_CLASS::INT=263;
const int YY_parse_CLASS::FLOAT=264;
const int YY_parse_CLASS::CHAR=265;
const int YY_parse_CLASS::STRING=266;
const int YY_parse_CLASS::BOOL=267;
const int YY_parse_CLASS::DOUBLE=268;
const int YY_parse_CLASS::LONG=269;
const int YY_parse_CLASS::VOID=270;
const int YY_parse_CLASS::NODE=271;
const int YY_parse_CLASS::BTREE=272;
const int YY_parse_CLASS::BSTREE=273;
const int YY_parse_CLASS::COMMA=274;
const int YY_parse_CLASS::LFB=275;
const int YY_parse_CLASS::RFB=276;
const int YY_parse_CLASS::SEMICOLON=277;
const int YY_parse_CLASS::LSB=278;
const int YY_parse_CLASS::RSB=279;
const int YY_parse_CLASS::NUMBER=280;
const int YY_parse_CLASS::EQUAL=281;
const int YY_parse_CLASS::AND=282;
const int YY_parse_CLASS::OR=283;
const int YY_parse_CLASS::LOR=284;
const int YY_parse_CLASS::LAND=285;
const int YY_parse_CLASS::LXOR=286;
const int YY_parse_CLASS::GEQ=287;
const int YY_parse_CLASS::LEQ=288;
const int YY_parse_CLASS::NE=289;
const int YY_parse_CLASS::EQ=290;
const int YY_parse_CLASS::STRINGC=291;
const int YY_parse_CLASS::CHARC=292;
const int YY_parse_CLASS::ADD=293;
const int YY_parse_CLASS::SUB=294;
const int YY_parse_CLASS::MUL=295;
const int YY_parse_CLASS::DIV=296;
const int YY_parse_CLASS::MOD=297;
const int YY_parse_CLASS::DECIMAL=298;
const int YY_parse_CLASS::FLOATING=299;
const int YY_parse_CLASS::DOT=300;
const int YY_parse_CLASS::BREAK=301;
const int YY_parse_CLASS::CONTINUE=302;
const int YY_parse_CLASS::RETURN=303;
const int YY_parse_CLASS::INCR=304;
const int YY_parse_CLASS::DECR=305;
const int YY_parse_CLASS::IF=306;
const int YY_parse_CLASS::ELSE=307;
const int YY_parse_CLASS::WHILE=308;
const int YY_parse_CLASS::FOR=309;
const int YY_parse_CLASS::LNULL=310;
const int YY_parse_CLASS::NEG=311;
const int YY_parse_CLASS::LTRUE=312;
const int YY_parse_CLASS::LFALSE=313;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		242
#define	YYFLAG		-32768
#define	YYNTBASE	59

#define YYTRANSLATE(x) ((unsigned)(x) <= 313 ? yytranslate[x] : 107)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50,    51,    52,    53,    54,    55,
    56,    57,    58
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     3,     6,     9,    12,    15,    16,    18,    20,
    22,    24,    31,    38,    48,    50,    52,    54,    56,    58,
    60,    62,    64,    66,    68,    70,    74,    77,    83,    90,
    97,   107,   110,   114,   116,   119,   121,   123,   125,   127,
   129,   131,   133,   135,   138,   141,   147,   153,   162,   164,
   168,   171,   176,   184,   186,   188,   191,   194,   197,   200,
   203,   206,   209,   210,   212,   214,   218,   224,   226,   228,
   230,   232,   234,   236,   238,   240,   242,   244,   246,   249,
   252,   253,   255,   257,   259,   261,   263,   265,   267,   269,
   271,   275,   280,   287,   291,   293,   297,   299,   303,   305,
   307,   309,   314,   316,   320,   323,   326,   329,   335,   343,
   345,   347,   353,   362,   365,   369,   371,   374,   376,   378,
   380,   382,   384,   386,   388,   391,   394,   396,   398,   400,
   404,   408,   410,   413,   416,   420
};

static const short yyrhs[] = {    -1,
    60,     0,    62,    61,     0,    68,    61,     0,    62,    61,
     0,    68,    61,     0,     0,    72,     0,    94,     0,    96,
     0,    63,     0,    64,     3,     4,    66,     5,    22,     0,
    15,     3,     4,    66,     5,    22,     0,    65,     6,    64,
     7,     3,     4,    66,     5,    22,     0,     8,     0,     9,
     0,    10,     0,    11,     0,    12,     0,    13,     0,    14,
     0,    16,     0,    17,     0,    18,     0,    67,     0,    66,
    19,    67,     0,    64,     3,     0,    65,     6,    64,     7,
     3,     0,    64,     3,     4,    66,     5,    69,     0,    15,
     3,     4,    66,     5,    69,     0,    65,     6,    64,     7,
     3,     4,    66,     5,    69,     0,    20,    21,     0,    20,
    70,    21,     0,    71,     0,    70,    71,     0,    72,     0,
    75,     0,    94,     0,    96,     0,    97,     0,    98,     0,
   106,     0,    69,     0,    73,    22,     0,    64,    74,     0,
    65,     6,    64,     7,    74,     0,    64,     3,    23,    25,
    24,     0,    65,     6,    64,     7,     3,    23,    25,    24,
     0,     3,     0,    74,    19,     3,     0,    76,    22,     0,
    64,     3,    26,    77,     0,    65,     6,    64,     7,     3,
    26,    91,     0,    78,     0,    79,     0,    56,    79,     0,
    81,    80,     0,    27,    79,     0,    28,    79,     0,    29,
    79,     0,    30,    79,     0,    31,    79,     0,     0,    82,
     0,    84,     0,    84,    83,    84,     0,     4,    84,    83,
    84,     5,     0,    57,     0,    58,     0,     6,     0,     7,
     0,    32,     0,    33,     0,    34,     0,    35,     0,    36,
     0,    37,     0,    85,     0,    88,    86,     0,    87,    85,
     0,     0,    38,     0,    39,     0,    40,     0,    41,     0,
    42,     0,     3,     0,    43,     0,    44,     0,    89,     0,
     4,    85,     5,     0,     3,     4,    90,     5,     0,     3,
    45,     3,     4,    90,     5,     0,    90,    19,    78,     0,
    78,     0,    20,    92,    21,     0,     3,     0,    92,    19,
    93,     0,    93,     0,    77,     0,    55,     0,     3,    26,
    95,    22,     0,    77,     0,    20,    92,    21,     0,     3,
    49,     0,     3,    50,     0,    95,    22,     0,    51,     4,
    78,     5,    69,     0,    51,     4,    78,     5,    69,    52,
    69,     0,    99,     0,   100,     0,    53,     4,    78,     5,
   101,     0,    54,     4,   104,    22,    78,    22,   105,   101,
     0,    20,    21,     0,    20,   102,    21,     0,   103,     0,
   102,   103,     0,    72,     0,    75,     0,    94,     0,    96,
     0,    97,     0,    98,     0,   106,     0,    46,    22,     0,
    47,    22,     0,    69,     0,    73,     0,    76,     0,     3,
    26,    95,     0,     3,    26,    95,     0,    78,     0,     3,
    49,     0,     3,    50,     0,    48,    78,    22,     0,    48,
    22,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    93,    94,    97,    98,   101,   102,   103,   106,   107,   108,
   109,   112,   113,   114,   117,   118,   119,   120,   121,   122,
   123,   126,   127,   128,   131,   132,   135,   136,   139,   140,
   141,   144,   145,   148,   149,   152,   153,   154,   155,   156,
   157,   158,   159,   162,   165,   166,   167,   168,   171,   172,
   175,   178,   179,   182,   185,   188,   189,   192,   193,   194,
   195,   196,   197,   200,   203,   204,   205,   206,   207,   210,
   211,   212,   213,   214,   215,   218,   219,   220,   223,   226,
   227,   230,   231,   232,   233,   234,   237,   238,   239,   240,
   241,   244,   245,   248,   249,   252,   253,   256,   257,   260,
   261,   264,   267,   268,   269,   270,   273,   276,   277,   280,
   281,   284,   287,   290,   291,   294,   295,   298,   299,   300,
   301,   302,   303,   304,   305,   306,   307,   310,   311,   312,
   315,   316,   317,   318,   321,   322
};

static const char * const yytname[] = {   "$","error","$illegal.","ID","LPAR",
"RPAR","LT","GT","INT","FLOAT","CHAR","STRING","BOOL","DOUBLE","LONG","VOID",
"NODE","BTREE","BSTREE","COMMA","LFB","RFB","SEMICOLON","LSB","RSB","NUMBER",
"EQUAL","AND","OR","LOR","LAND","LXOR","GEQ","LEQ","NE","EQ","STRINGC","CHARC",
"ADD","SUB","MUL","DIV","MOD","DECIMAL","FLOATING","DOT","BREAK","CONTINUE",
"RETURN","INCR","DECR","IF","ELSE","WHILE","FOR","LNULL","NEG","LTRUE","LFALSE",
"start","program","pr","global_stmt","func_dec","pt_allowed","np_datatype","func_args",
"func_arg","func","block","statements","statement","declaration_stmt","declaration",
"id_list","intialisation_stmt","intialisation","inpt_rhs","predicate","conditions",
"cond","condition","con_posm","ops","con_pos","acon_posm","acond","aops","acon_pos",
"func_call","call_args","innp_rhs","init_args","init_arg","assignment","expr",
"expression","conditional_stmt","loop_stmt","while_loop","for_loop","loop_block",
"loop_statements","loop_statement","for_f","for_l","return_stmt",""
};
#endif

static const short yyr1[] = {     0,
    59,    59,    60,    60,    61,    61,    61,    62,    62,    62,
    62,    63,    63,    63,    64,    64,    64,    64,    64,    64,
    64,    65,    65,    65,    66,    66,    67,    67,    68,    68,
    68,    69,    69,    70,    70,    71,    71,    71,    71,    71,
    71,    71,    71,    72,    73,    73,    73,    73,    74,    74,
    75,    76,    76,    77,    78,    79,    79,    80,    80,    80,
    80,    80,    80,    81,    82,    82,    82,    82,    82,    83,
    83,    83,    83,    83,    83,    84,    84,    84,    85,    86,
    86,    87,    87,    87,    87,    87,    88,    88,    88,    88,
    88,    89,    89,    90,    90,    91,    91,    92,    92,    93,
    93,    94,    95,    95,    95,    95,    96,    97,    97,    98,
    98,    99,   100,   101,   101,   102,   102,   103,   103,   103,
   103,   103,   103,   103,   103,   103,   103,   104,   104,   104,
   105,   105,   105,   105,   106,   106
};

static const short yyr2[] = {     0,
     0,     1,     2,     2,     2,     2,     0,     1,     1,     1,
     1,     6,     6,     9,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     3,     2,     5,     6,     6,
     9,     2,     3,     1,     2,     1,     1,     1,     1,     1,
     1,     1,     1,     2,     2,     5,     5,     8,     1,     3,
     2,     4,     7,     1,     1,     2,     2,     2,     2,     2,
     2,     2,     0,     1,     1,     3,     5,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     2,     2,
     0,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     3,     4,     6,     3,     1,     3,     1,     3,     1,     1,
     1,     4,     1,     3,     2,     2,     2,     5,     7,     1,
     1,     5,     8,     2,     3,     1,     2,     1,     1,     1,
     1,     1,     1,     1,     2,     2,     1,     1,     1,     3,
     3,     1,     2,     2,     3,     2
};

static const short yydefact[] = {     1,
    87,     0,    15,    16,    17,    18,    19,    20,    21,     0,
    22,    23,    24,     0,    76,    77,    88,    89,     0,    68,
    69,     2,     7,    11,     0,     0,     7,     8,     0,   103,
    54,    55,    63,    64,    65,    78,    81,    90,     9,     0,
    10,     0,     0,     0,   105,   106,    87,     0,     0,    78,
     0,   101,   100,     0,    99,    56,     3,     7,     7,    49,
    45,     0,     4,    44,     0,     0,     0,     0,     0,    57,
    70,    71,    72,    73,    74,    75,     0,    82,    83,    84,
    85,    86,    79,     0,   107,    95,     0,    87,     0,     0,
     0,     0,    91,     0,     0,   104,     5,     6,     0,     0,
     0,     0,    58,    59,    60,    61,    62,    66,    80,    92,
     0,   102,     0,     0,     0,     0,     0,    25,    98,     0,
     0,    50,     0,    94,     0,    67,    27,     0,     0,     0,
     0,    47,    49,    46,    93,     0,     0,    13,    30,    26,
    12,    29,     0,     0,     0,     0,    32,     0,     0,     0,
     0,     0,     0,    43,     0,    34,    36,    37,     0,    38,
    39,    40,    41,   110,   111,    42,     0,     0,    28,   100,
   136,     0,     0,     0,     0,    49,     0,    33,    35,    51,
     0,    48,   135,     0,     0,     0,   128,   129,     0,     0,
     0,    14,    31,     0,     0,     0,     0,    52,     0,   108,
     0,   112,   130,     0,    49,     0,   114,     0,     0,   127,
   118,   119,   120,   121,   122,   123,     0,   116,   124,     0,
     0,   109,   125,   126,   115,   117,    87,   132,     0,    97,
     0,    53,     0,   133,   134,   113,     0,   131,    96,     0,
     0,     0
};

static const short yydefgoto[] = {   240,
    22,    57,    58,    24,   152,   153,   117,   118,    59,   154,
   155,   156,    28,    29,    61,   158,   159,    30,    31,    32,
    70,    33,    34,    77,    35,    36,    83,    84,    37,    38,
    87,   232,    54,    55,    39,    40,    41,   162,   163,   164,
   165,   202,   217,   218,   189,   229,   166
};

static const short yypact[] = {   434,
    42,   149,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    38,
-32768,-32768,-32768,    86,-32768,-32768,-32768,-32768,   463,-32768,
-32768,-32768,   434,-32768,    44,    54,   434,-32768,    45,-32768,
-32768,-32768,   214,-32768,   205,-32768,   194,-32768,-32768,    48,
-32768,   463,   437,    61,-32768,-32768,     6,    18,   205,    72,
    99,-32768,-32768,    88,-32768,-32768,-32768,   434,   434,     8,
    85,   392,-32768,-32768,   463,   463,   463,   463,   463,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   149,-32768,-32768,-32768,
-32768,-32768,-32768,    18,-32768,-32768,    40,    76,    98,   120,
    72,   149,-32768,   336,    86,-32768,-32768,-32768,   336,   102,
   128,   132,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
   463,-32768,   463,   135,   145,   161,    92,-32768,-32768,    97,
   134,-32768,   168,-32768,   100,-32768,-32768,   392,   116,   336,
   125,-32768,    19,    85,-32768,   167,   322,-32768,-32768,-32768,
-32768,-32768,   336,   153,   176,   266,-32768,   460,   177,   178,
   179,   184,   188,-32768,   378,-32768,-32768,-32768,   175,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   109,   166,-32768,   180,
-32768,   182,   463,   463,   282,    -9,   392,-32768,-32768,-32768,
   129,-32768,-32768,   196,   202,   189,-32768,-32768,   203,   463,
   209,-32768,-32768,   228,   229,   437,   463,-32768,   226,   198,
   152,-32768,-32768,   230,    14,   228,-32768,   233,   237,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   210,-32768,-32768,   498,
     5,-32768,-32768,-32768,-32768,-32768,    68,-32768,   229,-32768,
    86,-32768,   437,-32768,-32768,-32768,   156,-32768,-32768,   251,
   260,-32768
};

static const short yypgoto[] = {-32768,
-32768,    -1,   262,-32768,     7,    16,   -94,   141,   265,  -118,
-32768,   117,  -122,   106,  -114,  -182,   113,   -14,   -40,   -13,
-32768,-32768,-32768,   224,     1,     2,-32768,-32768,-32768,-32768,
   191,-32768,    58,   206,  -119,   -42,  -117,  -173,  -169,-32768,
-32768,    77,-32768,    80,-32768,-32768,  -105
};


#define	YYLAST		556


static const short yytable[] = {    53,
    89,    86,    49,    50,   120,    56,    25,   230,   134,    42,
   139,    99,   142,   100,   157,    26,   190,   160,   212,   161,
    47,    48,   143,   157,   231,    63,   160,   215,   161,    25,
   100,   216,   157,    25,   212,   160,   144,   161,    26,   221,
    51,   144,    26,   215,   110,    42,    60,   216,   167,    91,
    44,   103,   104,   105,   106,   107,    97,    98,   111,    62,
    17,    18,   193,    90,    25,    25,    64,    43,   102,    85,
   124,    42,    86,    26,    26,   200,    93,   108,   211,    42,
    53,   213,   210,   214,   134,   109,    44,   222,    47,     2,
    45,    46,   114,   233,   211,   219,   129,   213,   210,   214,
   115,   131,    94,   101,   135,   115,    95,   172,    96,   116,
   130,   219,    44,   181,   116,   130,   234,   235,   111,   112,
    44,    15,    16,   113,    45,    46,   121,   130,    17,    18,
   122,   170,   184,   185,   136,   137,   115,   138,   123,   126,
    52,    19,    20,    21,   137,   116,   141,   127,   137,   115,
   192,    47,    48,   203,     1,     2,   204,   132,   116,     3,
     4,     5,     6,     7,     8,     9,   128,    11,    12,    13,
   133,   146,   207,   145,    95,   198,   239,   168,   169,   228,
   173,   174,   175,   191,    15,    16,   176,    15,    16,   182,
   238,    17,    18,   177,    17,    18,   180,   208,   209,   148,
   194,  -103,   149,   183,   150,   151,   195,    19,    20,    21,
    71,    72,     1,     2,   196,   199,    53,     3,     4,     5,
     6,     7,     8,     9,   197,    11,    12,    13,   205,   146,
   225,    78,    79,    80,    81,    82,    73,    74,    75,    76,
    65,    66,    67,    68,    69,    15,    16,   137,   201,   206,
   241,   220,    17,    18,   223,   208,   209,   148,   224,   242,
   149,    23,   150,   151,    27,    19,    20,    21,     1,     2,
   140,   179,    92,     3,     4,     5,     6,     7,     8,     9,
   187,    11,    12,    13,   186,   146,   147,   188,   237,     3,
     4,     5,     6,     7,     8,     9,   226,    11,    12,    13,
   119,    15,    16,   125,     0,   236,     0,     0,    17,    18,
     0,     0,     0,   148,     0,     0,   149,     0,   150,   151,
    52,    19,    20,    21,     1,     2,     0,     0,     0,     3,
     4,     5,     6,     7,     8,     9,     0,    11,    12,    13,
     0,   146,   147,     3,     4,     5,     6,     7,     8,     9,
     0,    11,    12,    13,     0,     0,     0,    15,    16,     0,
     0,     0,     0,     0,    17,    18,     0,     0,     0,   148,
     0,     0,   149,     0,   150,   151,     0,    19,    20,    21,
     1,     2,     0,     0,     0,     3,     4,     5,     6,     7,
     8,     9,     0,    11,    12,    13,     0,   146,   178,     3,
     4,     5,     6,     7,     8,     9,     0,     0,     0,     0,
     0,     0,     0,    15,    16,     0,     0,     0,     0,     0,
    17,    18,     0,     0,     0,   148,     0,     0,   149,     0,
   150,   151,     0,    19,    20,    21,     1,     2,     0,    88,
     2,     3,     4,     5,     6,     7,     8,     9,    10,    11,
    12,    13,     0,    14,     0,     0,    14,     0,     0,     0,
     0,     0,    47,     2,     0,    47,     2,     0,     0,    15,
    16,     0,    15,    16,     0,     0,    17,    18,     0,    17,
    18,   171,     0,     0,     0,     0,     0,     0,     0,    19,
    20,    21,    19,    20,    21,    15,    16,     0,    15,    16,
   227,     2,    17,    18,     0,    17,    18,     0,     0,     0,
     0,     0,     0,     0,     0,    19,    20,    21,    19,    20,
    21,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    15,    16,     0,     0,     0,     0,     0,
    17,    18,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    19,    20,    21
};

static const short yycheck[] = {    14,
    43,    42,     2,     2,    99,    19,     0,     3,   123,     4,
   129,     4,   131,    23,   137,     0,    26,   137,   201,   137,
     3,     4,     4,   146,    20,    27,   146,   201,   146,    23,
    23,   201,   155,    27,   217,   155,    23,   155,    23,    26,
     3,    23,    27,   217,     5,     4,     3,   217,   143,    48,
    45,    65,    66,    67,    68,    69,    58,    59,    19,     6,
    43,    44,   181,     3,    58,    59,    22,    26,    62,    22,
   111,     4,   113,    58,    59,   194,     5,    77,   201,     4,
    95,   201,   201,   201,   199,    84,    45,   206,     3,     4,
    49,    50,    92,    26,   217,   201,     5,   217,   217,   217,
    94,     5,     4,    19,     5,    99,    19,   148,    21,    94,
    19,   217,    45,     5,    99,    19,    49,    50,    19,    22,
    45,    36,    37,     4,    49,    50,    25,    19,    43,    44,
     3,   146,   173,   174,   128,    20,   130,    22,     7,     5,
    55,    56,    57,    58,    20,   130,    22,     3,    20,   143,
    22,     3,     4,   196,     3,     4,   197,    24,   143,     8,
     9,    10,    11,    12,    13,    14,     6,    16,    17,    18,
     3,    20,    21,     7,    19,   190,    21,    25,     3,   220,
     4,     4,     4,   177,    36,    37,     3,    36,    37,    24,
   233,    43,    44,     6,    43,    44,    22,    46,    47,    48,
     5,    22,    51,    22,    53,    54,     5,    56,    57,    58,
     6,     7,     3,     4,    26,     7,   231,     8,     9,    10,
    11,    12,    13,    14,    22,    16,    17,    18,     3,    20,
    21,    38,    39,    40,    41,    42,    32,    33,    34,    35,
    27,    28,    29,    30,    31,    36,    37,    20,    20,    52,
     0,    22,    43,    44,    22,    46,    47,    48,    22,     0,
    51,     0,    53,    54,     0,    56,    57,    58,     3,     4,
   130,   155,    49,     8,     9,    10,    11,    12,    13,    14,
   175,    16,    17,    18,     3,    20,    21,   175,   231,     8,
     9,    10,    11,    12,    13,    14,   217,    16,    17,    18,
    95,    36,    37,   113,    -1,   229,    -1,    -1,    43,    44,
    -1,    -1,    -1,    48,    -1,    -1,    51,    -1,    53,    54,
    55,    56,    57,    58,     3,     4,    -1,    -1,    -1,     8,
     9,    10,    11,    12,    13,    14,    -1,    16,    17,    18,
    -1,    20,    21,     8,     9,    10,    11,    12,    13,    14,
    -1,    16,    17,    18,    -1,    -1,    -1,    36,    37,    -1,
    -1,    -1,    -1,    -1,    43,    44,    -1,    -1,    -1,    48,
    -1,    -1,    51,    -1,    53,    54,    -1,    56,    57,    58,
     3,     4,    -1,    -1,    -1,     8,     9,    10,    11,    12,
    13,    14,    -1,    16,    17,    18,    -1,    20,    21,     8,
     9,    10,    11,    12,    13,    14,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    36,    37,    -1,    -1,    -1,    -1,    -1,
    43,    44,    -1,    -1,    -1,    48,    -1,    -1,    51,    -1,
    53,    54,    -1,    56,    57,    58,     3,     4,    -1,     3,
     4,     8,     9,    10,    11,    12,    13,    14,    15,    16,
    17,    18,    -1,    20,    -1,    -1,    20,    -1,    -1,    -1,
    -1,    -1,     3,     4,    -1,     3,     4,    -1,    -1,    36,
    37,    -1,    36,    37,    -1,    -1,    43,    44,    -1,    43,
    44,    22,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    56,
    57,    58,    56,    57,    58,    36,    37,    -1,    36,    37,
     3,     4,    43,    44,    -1,    43,    44,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    56,    57,    58,    56,    57,
    58,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    36,    37,    -1,    -1,    -1,    -1,    -1,
    43,    44,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    56,    57,    58
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 325 "Yacc.y"

int yywrap(){} // Defining yywrap function (no action required)

int main(int argc, char* argv[]) {
    fsread = fopen(argv[1], "r"); // Open the input file
    char s[20];
    sprintf(s, "seq_tokens_%c.txt", argv[1][0]);
    fswrite = fopen(s, "w"); // Open the token output file
    yyin = fsread; // Set the input file for the lexer
    yyparse(); // Start the parsing process
    fclose(fsread); // Close the input file
    fclose(fswrite); // Close the token output file
    return 0;
}

int yyerror() {
        printf("Invalid statement\n"); // Defining error handling for syntax errors
        exit(1);
}
